---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels: &labels
    app.kubernetes.io/component: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: nfs-media
          persistentVolumeClaim:
            claimName: nfs-media
      containers:
        - name: manyfold
          image: ghcr.io/manyfold3d/manyfold:0.111.2@sha256:ac59d8392f0728c66555a8846fa11892f1fa36558c3dea70fe2ae8b6f42e4219
          env:
            - name: DATABASE_ADAPTER
              value: postgresql
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: manyfold-secret
                  key: SECRET_KEY_BASE
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: manyfold-postgres-app
                  key: password
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: manyfold-postgres-app
                  key: username
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: manyfold-postgres-app
                  key: dbname
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: manyfold-postgres-app
                  key: host
            - name: REDIS_URL
              value: redis://manyfold-valkey-service:6379
          volumeMounts:
            - name: nfs-media
              mountPath: /media
          ports:
            - name: http
              containerPort: 3214
