---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  annotations:
    reloader.stakater.com/auto: 'true'
  labels: &labels
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      volumes:
        - name: config
          configMap:
            name: config
      containers:
        - name: starbase-80
          image: ghcr.io/notclickable-jordan/starbase-80:1.6.1@sha256:98ee82db69aadaebbc38d7d276197c53dd71c71a3543f36d5f032ae95c386c31
          resources:
            requests:
              memory: 100M
            limits:
              memory: 1G
          securityContext:
            privileged: false
          volumeMounts:
            - name: config
              mountPath: /app/src/config/config.json
              subPath: config.json
              readOnly: true
          env:
            - name: ICON
              value: mdi-home
            - name: TITLE
              value: durbin.casa
            - name: TZ
              value: America/Denver
          ports:
            - name: http
              containerPort: 4173
