---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels: &labels
    app.kubernetes.io/component: box
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: volume
      containers:
        - name: dev
          image: quay.io/fedora/fedora:43@sha256:9ca315d2f307b838dd29037110c519f647c5b8b1ac90a1e4ce4023899f7b7167
          command: ['/bin/bash', '-c', '--']
          args: ['while true; do sleep 30; done;']
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop: [ALL]
          volumeMounts:
            - name: volume
              mountPath: /volume
