---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels: &labels
    app.kubernetes.io/component: box
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: volume
      containers:
        - name: dev
          image: quay.io/fedora/fedora:42@sha256:9b90ee776a0190817d1c6a1d72afae3e501e573f86a7844ec1195b18f2bc50e8
          command: ['/bin/bash', '-c', '--']
          args: ['while true; do sleep 30; done;']
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop: [ALL]
          volumeMounts:
            - name: volume
              mountPath: /volume
