---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels: &labels
    app.kubernetes.io/component: box
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: volume
      containers:
        - name: dev
          image: quay.io/fedora/fedora:43@sha256:ae43b5dfbe4d32322e197e92633dfb6a6ec0062ca0b049244fbacbe5864dc417
          command: ['/bin/bash', '-c', '--']
          args: ['while true; do sleep 30; done;']
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop: [ALL]
          volumeMounts:
            - name: volume
              mountPath: /volume
