---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: In
        values:
          - 'true'
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade:v1.32.2-k3s1@sha256:14f94ccaedf2ee7373afc4638a7428d8326e2ea561805bab7ac75e77518804c5
  channel: https://update.k3s.io/v1-release/channels/stable

---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  prepare:
    args:
      - prepare
      - server-plan
    image: rancher/k3s-upgrade:v1.32.2-k3s1@sha256:14f94ccaedf2ee7373afc4638a7428d8326e2ea561805bab7ac75e77518804c5
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade:v1.32.2-k3s1@sha256:14f94ccaedf2ee7373afc4638a7428d8326e2ea561805bab7ac75e77518804c5
  channel: https://update.k3s.io/v1-release/channels/stable
