---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: In
        values:
          - 'true'
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade:v1.32.3-k3s1@sha256:b2705c34589c381414002deaf96c6cc6eb85b85bbce65f6444bf39bbee7ab39d
  channel: https://update.k3s.io/v1-release/channels/stable

---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: agent-plan
  namespace: system-upgrade
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  prepare:
    args:
      - prepare
      - server-plan
    image: rancher/k3s-upgrade:v1.32.3-k3s1@sha256:b2705c34589c381414002deaf96c6cc6eb85b85bbce65f6444bf39bbee7ab39d
  serviceAccountName: system-upgrade
  upgrade:
    image: rancher/k3s-upgrade:v1.32.3-k3s1@sha256:b2705c34589c381414002deaf96c6cc6eb85b85bbce65f6444bf39bbee7ab39d
  channel: https://update.k3s.io/v1-release/channels/stable
