FROM ghcr.io/kevindurb/dev

RUN sudo setenforce Permissive

RUN dnf install -y \
  openssh-server

RUN ssh-keygen -A \
    && echo -e "PasswordAuthentication no" >> /etc/ssh/sshd_config

RUN useradd -m kevindurb
RUN usermod -a -G wheel kevindurb
# RUN passwd -u kevindurb

USER kevindurb

RUN mkdir -p /home/kevindurb/.ssh \
    && chmod 0700 /home/kevindurb/.ssh

RUN wget -O /home/kevindurb/.ssh/authorized_keys https://github.com/kevindurb.keys \
  && chmod 0700 /home/kevindurb/.ssh/authorized_keys

USER root

ENTRYPOINT ["/usr/sbin/sshd", "-Dddd"]
