---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey-deployment
  labels: &labels
    app.kubernetes.io/component: valkey
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: valkey
          image: docker.io/valkey/valkey:8.1@sha256:b6fcb22adda4b48160311e3af30880f5dbea7d519980f08e57086fcfd8ea46d1
          resources:
            limits:
              memory: 1G
          ports:
            - name: valkey
              containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: valkey-service
spec:
  selector:
    app.kubernetes.io/component: valkey
  ports:
    - name: valkey
      port: 6379
      targetPort: valkey
