---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels: &labels
    app.kubernetes.io/component: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: volume
        - name: media
          persistentVolumeClaim:
            claimName: nfs-media
      containers:
        - name: calibre-web
          image: ghcr.io/linuxserver/calibre-web:0.6.24@sha256:978d38b0a03b5503630a8365047060e79d3304d8c336b9a23b1e87c4b15f8256
          securityContext:
            privileged: false
          resources:
            requests:
              memory: 300M
            limits:
              memory: 1G
          env:
            - name: TZ
              value: America/Denver
            - name: PUID
              value: '1000'
            - name: PGID
              value: '1000'
            - name: DOCKER_MODS
              value: linuxserver/mods:universal-calibre
          volumeMounts:
            - name: volume
              mountPath: /config
            - name: media
              subPath: eBooks
              mountPath: /books
          ports:
            - name: http
              containerPort: 8083
