---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      nodeSelector:
        optical-drives: 'true'
      containers:
        - image: jlesage/makemkv:v25.02.3@sha256:7952ff1ce7e6f7a4e2ce6bca6dd5141e8235be064613c7cc243b3de462a7972f
          name: makemkv
          env:
            - name: USER_ID
              value: '1000'
            - name: GROUP_ID
              value: '1000'
            - name: TZ
              value: America/Denver
          securityContext:
            privileged: true
          ports:
            - name: web
              containerPort: 5800
          volumeMounts:
            - name: media
              mountPath: /output
              subPath: Downloads
            - name: sr0
              mountPath: /dev/sr0
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: truenas-media
        - name: sr0
          hostPath:
            path: /dev/sr0

---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  ports:
    - name: web
      port: 80
      targetPort: web
