#! /bin/bash

export BW_SESSION=$(bw unlock --raw)

bw sync

bw get notes 'infra .env' > .env
echo "'infra .env' note written to '.env'"

bw get notes 'infra secrets.yaml' > secrets.yaml
echo "'infra secrets.yaml' note written to 'secrets.yaml'"
