{
 "title": "Container Overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Active Pods",
   "type": "stat",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_active_pods{static!=\"true\", job=\"kubelet\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volume Usage By Node",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container!=''}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sort_desc(container_memory_usage_bytes{container!=\"\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}